public class ExibirVariaveis {

    public static void main (String[] args) {
        int numeroInteiro = 10;

        double numeroFloat = 3.75;

        char letra = 's';

        boolean teste = true;

        //Exibir linha de comantando:

        System.out.println("numero inteiro: " + numeroInteiro);
        System.out.println("numero ponto flutuante: " + numeroFloat);
        System.out.println("letra: " + letra);
        System.out.println("Boolean: " + teste);
    }

}